const dated = (value) => value && Number.isFinite(Date.parse(value));
const known = (value) => Number.isFinite(value) && value >= 0;
const dayKey = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Seoul', year: 'numeric', month: '2-digit', day: '2-digit' });
// These exact descriptions were generated by the old revision backfill, which
// interpolated counts instead of reading the presentation at each revision.
const estimatedLegacy = (record) => record?.source === 'legacy_unverified' && /^(?:\[작성\] 슬라이드 본문 작성 \(\+\d+자\)|\[편집\] 슬라이드 개체 및 이미지 자료 배치)$/.test(String(record.raw?.[6] || ''));

export function legacyChangeBins(records, metric = 'charCount', grouping = 'day', baseline = null) {
  if (!['charCount', 'imageCount', 'slideCount'].includes(metric)) throw new Error('알 수 없는 기록 수치입니다.');
  const rows = records.filter((row) => row.source === 'legacy_unverified' && dated(row.checkedAt))
    .slice().sort((a, b) => Date.parse(a.checkedAt) - Date.parse(b.checkedAt));
  const bins = new Map();
  let previous = null;
  for (const row of rows) {
    const date = dayKey.format(new Date(row.checkedAt));
    const id = grouping === 'day' ? `legacy-day:${date}` : `legacy-record:${row.id || bins.size}`;
    if (!bins.has(id)) bins.set(id, { id, label: `${Number(date.slice(5, 7))}/${Number(date.slice(8, 10))}`, start: previous?.checkedAt || row.checkedAt,
      end: row.checkedAt, added: 0, removed: 0, records: [], comparisons: [], reference: !previous, unknown: 0 });
    const bin = bins.get(id);
    bin.end = row.checkedAt;
    bin.records.push(row);
    let difference = null, templateAdjusted = false, templateReference = false;
    if (previous && Date.parse(row.checkedAt) > Date.parse(previous.checkedAt) && known(previous[metric]) && known(row[metric])) {
      difference = row[metric] - previous[metric];
      const initialTemplateAppears = metric !== 'slideCount' && dated(baseline?.recordedAt) && Date.parse(row.checkedAt) < Date.parse(baseline.recordedAt) && known(baseline.chars) && baseline.chars > 0 && known(baseline.images) && baseline.images > 0 &&
        known(previous.charCount) && known(previous.imageCount) && previous.charCount < baseline.chars && previous.imageCount < baseline.images && row.charCount - previous.charCount >= baseline.chars && row.imageCount >= baseline.images;
      if (initialTemplateAppears) {
        // A previously blank file acquiring the initial template is another
        // reference state. Do not attribute that bundle to student work.
        difference = null;
        templateReference = true;
        bin.reference = true;
      }
      const crossesBaseline = metric !== 'slideCount' && dated(baseline?.recordedAt) && Date.parse(previous.checkedAt) < Date.parse(baseline.recordedAt) && Date.parse(row.checkedAt) >= Date.parse(baseline.recordedAt);
      const template = metric === 'charCount' ? baseline?.chars : baseline?.images;
      if (crossesBaseline && known(template) && template > 0 && previous[metric] >= template) {
        // Old code switched from totals to template-excluded amounts. Only
        // reconcile the explicit downward switch; ambiguous transitions stay unknown.
        if (row[metric] < template && known(baseline?.chars) && known(baseline?.images) && previous.charCount >= baseline.chars && previous.imageCount >= baseline.images) {
          difference = row[metric] - (previous[metric] - template);
          templateAdjusted = true;
        } else difference = null;
      }
    }
    if (difference !== null) {
      bin.added += Math.max(0, difference);
      bin.removed += Math.max(0, -difference);
    } else if (previous) bin.unknown++;
    bin.comparisons.push({ previous, current: row, difference, templateAdjusted, templateReference });
    previous = row;
  }
  return [...bins.values()];
}

// Keep the full period in one plot. Adjacent intervals are combined only for
// display, preserving their actual bounds and every underlying record.
export function compactChartBins(bins, limit = 48) {
  if (bins.length <= limit) return bins;
  const size = Math.ceil(bins.length / limit), result = [];
  for (let index = 0; index < bins.length; index += size) {
    const group = bins.slice(index, index + size);
    result.push({ id: `group:${group[0].id}:${group.at(-1).id}`, label: `${group[0].label}–${group.at(-1).label}`,
      start: group[0].start, end: group.at(-1).end,
      added: group.reduce((sum, bin) => sum + bin.added, 0), removed: group.reduce((sum, bin) => sum + bin.removed, 0),
      records: group.flatMap((bin) => bin.records), comparisons: group.flatMap((bin) => bin.comparisons || []),
      activities: group.flatMap((bin) => bin.activities || []),
      imageAdded: group.reduce((sum, bin) => sum + (bin.imageAdded || 0), 0), imageRemoved: group.reduce((sum, bin) => sum + (bin.imageRemoved || 0), 0),
      slideAdded: group.reduce((sum, bin) => sum + (bin.slideAdded || 0), 0), slideRemoved: group.reduce((sum, bin) => sum + (bin.slideRemoved || 0), 0),
      textUncertain: group.some((bin) => bin.textUncertain),
      unknown: group.reduce((sum, bin) => sum + (bin.unknown || 0), 0), reference: group.some((bin) => bin.reference) });
  }
  return result;
}

// Compare each format on its own terms before placing the results on one timeline.
// A new snapshot never subtracts a legacy count with a different counting basis.
export function studentActivityTimeline(records, baseline = null) {
  const rows = records.filter((record) => dated(record.checkedAt)).slice().sort((a, b) => Date.parse(a.checkedAt) - Date.parse(b.checkedAt));
  if (!rows.length) return { bins: [], start: null, end: null };
  const legacy = ['charCount', 'imageCount', 'slideCount'].map((metric) => new Map(legacyChangeBins(rows, metric, 'record', baseline).map((bin) => [bin.records[0], bin.comparisons[0]])));
  const short = Date.parse(rows.at(-1).checkedAt) - Date.parse(rows[0].checkedAt) <= 48 * 3600000;
  const groups = new Map();
  let previousSnapshot = null;
  for (const record of rows) {
    const comparisons = record.source === 'legacy_unverified' ? legacy.map((map) => map.get(record)) : null;
    const interval = dated(record.previousCheckedAt) && Date.parse(record.checkedAt) > Date.parse(record.previousCheckedAt);
    const deltas = comparisons ? comparisons.some((item) => item?.templateReference) ? [null, null, null] : comparisons.map((comparison) => comparison?.difference ?? null) : record.source === 'first_snapshot' || !interval ? [null, null, null] : [record.charDelta, record.imageDelta, record.slideDelta].map((value) => Number.isFinite(value) ? value : null);
    const previous = comparisons?.[0]?.previous || (previousSnapshot?.checkedAt === record.previousCheckedAt ? previousSnapshot : null);
    if (comparisons && (estimatedLegacy(record) || estimatedLegacy(previous))) deltas[0] = null;
    // A flat legacy count is not evidence that no text was written. The old
    // template subtraction and backfill could hide ongoing writing.
    const textUncertain = Boolean(comparisons && (deltas[0] === null || deltas[0] === 0));
    const pages = [];
    if (!comparisons && previous && Array.isArray(previous.pages) && Array.isArray(record.pages)) {
      const before = new Map(previous.pages.map((page) => [page.id, page]));
      for (const page of record.pages) {
        const prior = before.get(page.id);
        if (!prior) pages.push({ number: page.number, kind: 'added' });
        else if (known(page.chars) && known(prior.chars) && known(page.images) && known(prior.images) && (page.chars !== prior.chars || page.images !== prior.images)) pages.push({ number: page.number, kind: 'changed', chars: page.chars - prior.chars, images: page.images - prior.images });
        before.delete(page.id);
      }
      for (const page of before.values()) pages.push({ number: page.number, kind: 'removed' });
    }
    if (!comparisons) previousSnapshot = record;
    // Initial states and unchanged checks are not student work bars.
    if (!deltas.some((value) => Number.isFinite(value) && value !== 0) && !pages.length) continue;
    const date = dayKey.format(new Date(record.checkedAt));
    const bucket = short ? Math.floor(Date.parse(record.checkedAt) / 1200000) : date;
    const id = `activity:${bucket}`;
    const label = new Date(record.checkedAt).toLocaleString('ko-KR', { timeZone: 'Asia/Seoul', month: 'numeric', day: 'numeric', ...(short ? { hour: '2-digit', minute: '2-digit', hour12: false } : {}) });
    if (!groups.has(id)) groups.set(id, { id, label, start: previous?.checkedAt || record.previousCheckedAt || record.checkedAt, end: record.checkedAt, added: 0, removed: 0, imageAdded: 0, imageRemoved: 0, slideAdded: 0, slideRemoved: 0, textUncertain: false, records: [], activities: [] });
    const bin = groups.get(id);
    bin.end = record.checkedAt;
    bin.textUncertain ||= textUncertain;
    ['added', 'imageAdded', 'slideAdded'].forEach((field, index) => { bin[field] += Math.max(0, deltas[index] || 0); });
    ['removed', 'imageRemoved', 'slideRemoved'].forEach((field, index) => { bin[field] += Math.max(0, -(deltas[index] || 0)); });
    bin.records.push(record);
    bin.activities.push({ record, previousCheckedAt: previous?.checkedAt || record.previousCheckedAt, deltas, pages, textUncertain, templateAdjusted: comparisons?.some((item) => item?.templateAdjusted) || false });
  }
  const bins = compactChartBins([...groups.values()]);
  return { bins, start: rows[0].checkedAt, end: rows.at(-1).checkedAt, textUncertain: rows.some(estimatedLegacy) || bins.some((bin) => bin.textUncertain) };
}
